### ISSUE TITLE
audiodescribed/signed version downloaded instead of default version or "No programme versions found" / "No specified modes" warning shown

### ISSUE THREAD

**Issue by dinkypumpkin** [get-iplayer/get_iplayer#115]
From: https://squarepenguin.co.uk/forums/topic/pidindex-found-but-no-available-download/

Some programmes have multiple versions with the same name, but some of those duplicates do not have any associated media streams.  This means that some programmes will appear not to have a default version available, or audiodescribed/signed version may be downloaded instead of default.  All duplicates should be checked for available streams.  

Workaround: add `--playlist-metadata` to your get_player command to find default version (if it exists).

**Comment by alansharkey** [comment]
I had this issue too. I used the workaround "Workaround: add --playlist-metadata" successfully but it didn't download the episode number etc. i assume it's because of the -metadata.

Can I suggest an enhancement? If in the PVR Manager (I'm using the Windows version), under "program version", you add "-audiodescribed", then it won't look for audiodescribed at all. Is that possible?
