### ISSUE TITLE
iPlayer SD content OK.   HD streams 'retry' and never complete..

### ISSUE THREAD

**Issue by ayles2014** [get-iplayer/get_iplayer#119]
I have a feeling this might be a problem with the BBC streams, but just in case..:
I have been downloading HD content without any problems for some considerable time, but within the last few days, found that HD content frequently - and consistently - starts downloading OK, but then hits a certain percentage and then starts retrying, with repeated:
<b>ERROR: rtmp server sent error
ERROR: rtmp server requested close
INFO: Command exit code 1 (raw code = 256)</b>
Deleting the .flv file, and restarting the download, results in another series of retries at exactly the same percentage complete..
I tried watching the same programme directly on the BBC player (using Firefox) and the HD stream failed at exactly the same point..   Some programmes get to around 70% before failing, but others fail after only 5%..
When I switch the download for that programme to SD content, then there is no problem at all..
My usual download instruction is:
<code>get_iplayer --mode=best --proxy "http://xxxxxxxxxxxxxxxxxx" "<i>programme_name</i>"</code>

**Comment by dinkypumpkin** [comment]
Geo-blocking and possibly some server errors.  There is nothing get_player can do about either.  Since you didn't bother to provide an example, there is no way to test for problems with a particular stream, though that is unlikely in this case.  Since you appear to be using get_iplayer outside the UK, I can't help you any further.
