### ISSUE TITLE
AtomicParsley in get_iplayer v2.93 not compatible with 64-bit Windows 

### ISSUE THREAD

**Issue by Bruce-Delagi** [get-iplayer/get_iplayer#166]
On Windows 7 with get_iplayer 2.93

INFO: MP4 tagging MP4 file
This version of C:\Program Files (x86)\get_iplayer\AtomicParsley\atomicparsley.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
INFO: Command exit code 1 (raw code = 256)
WARNING: Failed to tag MP4 file

**Comment by dinkypumpkin** [comment]
Cannot reproduce.  The AtomicParsley build hasn't changed since v2.87 and has always worked on 64-bit Windows.  Somebody would have noticed if there were a general problem.  I don't know what is wrong on your system, so I can't offer any help.  If a full uninstall/reinstall doesn't help, then I suggest you post your query at:

https://squarepenguin.co.uk/forums/forum/windows-forums/windows-support/

Someone there may have experienced something similar.

**Comment by Bruce-Delagi** [comment]
Thanks I'll do that
