### ISSUE TITLE
Add redundant binmode() call for writing thumbnail file with obsolete perl versions

### ISSUE THREAD

**Issue by mcauser** [get-iplayer/get_iplayer#196]
Following on from https://github.com/get-iplayer/get_iplayer/issues/191

Fixed by adding `binmode($fh);` on line 5310.

```
# Write to file
unlink($file);
open( my $fh, ">:raw", $file );
binmode($fh);
print $fh $image;
close $fh;
```

This removes the error:
Wide character in print at get_iplayer line 5310.

**Comment by mcauser** [comment]
My Perl is a little rusty, but if this looks correct to you, I'll create a PR.

**Comment by dinkypumpkin** [comment]
I need a couple of things in order to proceed:

1. A reproducible test case.  The invocation of binmode() is redundant, so it may mask an underlying problem. There may be garbage data returned by BBC servers for certain programmes.  Since you're the only one who sees this, you need to tell me how to re-create the wide character warning. The example you posted in #191 was not reproducible, and that programme is now no longer available.
2. The output from this shell script:

    https://gist.github.com/dinkypumpkin/2e26225e314f0cef7818

    Scrub your username from the output if you wish.
