### ISSUE TITLE
git tags in the develop branch

### ISSUE THREAD

**Issue by dinkypumpkin** [get-iplayer/get_iplayer#266]
From @jon-hedgerows at: https://squarepenguin.co.uk/forums/thread-955-post-4290.html#pid4290

my build scripts determine a version number using
  git describe --tags --match v*

which would generate version numbers like v2.94-208-gc98e51c

and this has worked fine until now, mainly because up to v2.94 all the changes were happening in a single branch (master), and thus there was a single thread of change from the last tag to the latest, and even up until the release of v2.95 this still worked as following back down the develop branch eventually hit the last release tag (just before develop was branched out of master).

and this still works fine on the master branch
  $ git describe --tags --match v* master
  v2.95
and so the build scripts create the right version numbers for the "stable" builds I do.

but it doesn't work on the develop branch any more, because the commit that's tagged v2.95 is only on the master branch, so following back down the develop branch to the latest tag follows all the way back to v2.94, thus -
  $ git describe --tags --match v* develop
  v2.94-208-gc98e51c
whereas for the same commit I really want something like v2.95-3-gc98e51c

do any git gurus have any suggestions as to how to fix this?

thanks
Jon

**Comment by dinkypumpkin** [comment]
I can fix this with a forced push to develop, but I'll investigate further before making taking that route.

**Comment by jon-hedgerows** [comment]
I did some more digging since asking this question, and it appears (though I may be wrong) that the v2.95 commits are a merge of a set of changes, with the same set of changes applied to both the master and develop branches - i.e. two separate commits of the same changes.  The commit in the master branch is tagged v2.95, but the commit for the equivalent change in the develop branch isn't.  This has the effect of making the two branches the same, but by applying two consistent change sets rather than a merge.

doing this in the develop branch:
  `git merge --no-ff origin/master`
seems to put a connection back between the master and develop branches, such that the latest tag as seen on the develop branch is v2.95 (git describe develop seems to follow back across the merge and find the v2.95 tag with this in place).

**Comment by dinkypumpkin** [comment]
That was my first thought. I could also rebase the develop branch and do a forced push to make it look like it never happened. Since its the dev branch I don't really care about forcing updates. And I could also fix up the ancestry using `git replace`. One thing: you've already published builds with version numbers using 5 as the commit count, but the count in the `git describe` results after any of these changes would be <5. so your next few builds will have smaller version numbers than the current one. I purposely changed the tagging, but your setup slipped my mind. I'll change it back next around.

**Comment by dinkypumpkin** [comment]
The other options weren't really worth the bother, so I've just done a merge of master into develop.

Closed in 6b48739d6b942001e6dd5edd1a7cb2f3279de48b
